In [1]:
import numpy as np
import pandas as pd

# Output of a neuron with 3 inputs

In [2]:
inputs = [1.0, 2.0, 3.0]
weights = [0.2, 0.8, -0.5]
bias = 2.0
output = (inputs[0] * weights[0]
          + inputs[1] * weights[1]
          + inputs[2] * weights[2]
          + bias)
output

2.3

# Output of a neuron with 4 inputs

In [3]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
output = (inputs[0] * weights[0]
          + inputs[1] * weights[1]
          + inputs[2] * weights[2]
          + inputs[3] * weights[3]
          + bias)
output

4.8

# Layers of Neurons

In [4]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

outputs = [
    # Neuron 1:
    inputs[0] * weights[0][0] + 
    inputs[1] * weights[0][1] + 
    inputs[2] * weights[0][2] + 
    inputs[3] * weights[0][3] + biases[0],

    # Neuron 2:
    inputs[0] * weights[1][0] + 
    inputs[1] * weights[1][1] + 
    inputs[2] * weights[1][2] + 
    inputs[3] * weights[1][3] + biases[1],

    # Neuron 3:
    inputs[0] * weights[2][0] + 
    inputs[1] * weights[2][1] + 
    inputs[2] * weights[2][2] + 
    inputs[3] * weights[2][3] + biases[2],
]

outputs

[4.8, 1.21, 2.385]

#### Using loops

In [9]:
inputs = [1, 2, 3, 2.5]

# List of weights
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

# List of biases
biases = [2, 3, 0.5]

# Output of current layer
layer_outputs = []

# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    # zeroed output of given neuron
    neuron_output = 0

    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply this input by associated weight
        # and add to the neuron's output variable
        neuron_output += n_input * weight
    # add bias
    neuron_output += neuron_bias
    # put neuron's result to the layer's output list
    layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


# Single neuron using Numpy

In [15]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

# Calculate the dot product and add the bias
outputs1 = np.dot(weights_array, inputs_array) + bias
outputs2 = np.dot(inputs_array, weights_array) + bias
print(outputs1)
print(outputs2)

print("Both are same in vector multiplication")

4.8
4.8
Both are same in vector multiplication


## Layers of neurons using Numpy

In [17]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# Convert lists to numpy arrays
inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)

# Calculate the dot product anad add the biases
layer_outputs = np.dot(weights_array, inputs_array) + biases_array
print(layer_outputs)
print(weights_array.shape, inputs_array.shape)

[4.8   1.21  2.385]
(3, 4) (4,)


# Layer of neurons and batch of data using numpy

In [19]:
inputs = [[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# Calculate the dot product and add the biases
# NOTE: We can't TRANSPOSE lists in python, so we have to convert the weights matrix into an numpy array first.
outputs = np.dot(inputs_array, np.array(weights_array).T) + biases_array
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
